[package]
name = "solana-address-lookup-table-program"
version = "0.1.0"
description = "Solana Address Lookup Table Program"
authors = ["Anza Technology Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/address-lookup-table"
readme = "./README.md"
license-file = "../LICENSE"
edition = "2021"

[package.metadata.solana]
program-id = "AddressLookupTab1e1111111111111111111111111"

[features]
bpf-entrypoint = []
test-sbf = []

[dependencies]
bincode = "1.3.3"
bytemuck = "1.14.1"
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
solana-frozen-abi = "2.0.1"
solana-frozen-abi-macro = "2.0.1"
solana-program = "2.0.1"
spl-program-error = "0.5.0"

[dev-dependencies]
solana-program-test = "2.0.1"
solana-sdk = "2.0.1"
test-case = "3.3.1"

[lib]
crate-type = ["cdylib", "lib"]

[build-dependencies]
rustc_version = "0.4"
